/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import { apiURL } from "../../env";

import type { Theme } from "../model";

import { fetchWithAuth } from ".././fetchWithAuth.js";

export type getThemesResponse200 = {
    data: Theme[];
    status: 200;
};

export type getThemesResponseSuccess = getThemesResponse200 & {
    headers: Headers;
};
export type getThemesResponse = getThemesResponseSuccess;

export const getGetThemesUrl = () => {
    return `${apiURL}/api/themes`;
};

export const getThemes = async (options?: Parameters<typeof fetchWithAuth>[1]): Promise<getThemesResponse> => {
    return fetchWithAuth<getThemesResponse>(getGetThemesUrl(), {
        ...options,
        method: "GET",
    });
};
