import { Dialog } from 'geopf-extensions-openlayers';
import StyleForm from './styleForm.js';
import InputColor from './InputColor.js';

// Création du formulaire de style
const styleForm = new StyleForm();

styleForm.addCustomSelect({
  label: 'Forme',
  property: 'point-form',
  type: "form",
  options: {
    none: 'Sans',
    marker: 'Marqueur',
    circle: 'Cercle',
    square: 'Carré',
    triangle: 'Triangle',
  }
});
/* // Méthode temporaire
styleForm.addCustomSelect({
  label: 'Sélection',
  property: 'point-color',
  type: 'color',
  options: {
    "#ffcc33": "Jaune or",
    "#ffb03b": "Jaune orangé",
    "#ff7f00": "Orange",
    "#ff0000": "Rouge",
    "#ff8fc8": "Rose clair",
    "#ff24ff": "Magenta",
    "#2fde30": "Vert vif",
    "#97c005": "Vert anis",
    "#008900": "Vert foncé",
    "#00ff9a": "Vert menthe",
    "#12d8b6": "Turquoise",
    "#00ae91": "Vert sarcelle",
    "#00ffff": "Cyan",
    "#0a76f6": "Bleu",
    "#000091": "Bleu foncé",
    "#cc8bf9": "Violet clair",
    "#9a00ff": "Violet",
    "#bc6630": "Marron",
    "#ffffff": "Blanc",
    "#cdcdcd": "Gris clair",
    "#787878": "Gris",
    "#424242": "Gris foncé",
    "#000000": "Noir",
    "#00000000": "Sans couleur"
  }
});
*/
styleForm.addInput('Couleur', 'point-color', new InputColor());

styleForm.addCustomInput({
  label: 'Taille',
  property: 'point-radius',
});

styleForm.addBreak('point-form');
styleForm.addInput('Couleur', 'point-stroke-color', new InputColor());

styleForm.addCustomInput({
  label: 'Taille',
  property: 'point-stroke-width',
});

styleForm.addBreak('point-stroke');

styleForm.addCustomSelect({
  label: 'Symbole',
  property: 'point-glyph',
  type: 'icon',
  options: {
    " ": 'Sans',
    'ri-home-4-fill': 'home-4-fill',
    'ri-mail-add-fill': 'mail-add-fill',
    'ri-award-fill': 'award-fill',
    'ri-earth-fill': 'earth-fill',
    'ign-sport-marche': 'Marche',
    'ign-service-handicap': 'Handicape',
    "ri-24-hours-fill": "ri-24-hours-fill",
    "ri-4k-fill": "ri-4k-fill",
    "ri-accessibility-fill": "ri-accessibility-fill",
    "ri-account-box-2-fill": "ri-account-box-2-fill",
    "ri-account-box-fill": "ri-account-box-fill",
    "ri-account-circle-2-fill": "ri-account-circle-2-fill",
    "ri-account-circle-fill": "ri-account-circle-fill",
    "ri-account-pin-box-fill": "ri-account-pin-box-fill",
    "ri-account-pin-circle-fill": "ri-account-pin-circle-fill",
    "ri-add-box-fill": "ri-add-box-fill",
    "ri-add-circle-fill": "ri-add-circle-fill",
    "ri-add-fill": "ri-add-fill",
    "ri-add-large-fill": "ri-add-large-fill",
    "ri-admin-fill": "ri-admin-fill",
    "ri-advertisement-fill": "ri-advertisement-fill",
    "ri-aed-electrodes-fill": "ri-aed-electrodes-fill",
    "ri-aed-fill": "ri-aed-fill",
    "ri-ai-agent-fill": "ri-ai-agent-fill",
    "ri-ai-generate-2-fill": "ri-ai-generate-2-fill",
    "ri-ai-generate-3d-fill": "ri-ai-generate-3d-fill",
    "ri-airplay-fill": "ri-airplay-fill",
    "ri-alarm-add-fill": "ri-alarm-add-fill",
    "ri-alarm-fill": "ri-alarm-fill",
    "ri-alarm-snooze-fill": "ri-alarm-snooze-fill",
    "ri-alarm-warning-fill": "ri-alarm-warning-fill",
    "ri-album-fill": "ri-album-fill",
    "ri-alert-fill": "ri-alert-fill",
    "ri-alibaba-cloud-fill": "ri-alibaba-cloud-fill",
    "ri-aliens-fill": "ri-aliens-fill",
    "ri-align-item-bottom-fill": "ri-align-item-bottom-fill",
    "ri-align-item-horizontal-center-fill": "ri-align-item-horizontal-center-fill",
    "ri-align-item-left-fill": "ri-align-item-left-fill",
    "ri-align-item-right-fill": "ri-align-item-right-fill",
    "ri-align-item-top-fill": "ri-align-item-top-fill",
    "ri-align-item-vertical-center-fill": "ri-align-item-vertical-center-fill",
    "ri-alipay-fill": "ri-alipay-fill",
    "ri-amazon-fill": "ri-amazon-fill",
    "ri-anchor-fill": "ri-anchor-fill",
    "ri-ancient-gate-fill": "ri-ancient-gate-fill",
    "ri-ancient-pavilion-fill": "ri-ancient-pavilion-fill",
    "ri-android-fill": "ri-android-fill",
    "ri-angularjs-fill": "ri-angularjs-fill",
    "ri-anthropic-fill": "ri-anthropic-fill",
    "ri-anticlockwise-2-fill": "ri-anticlockwise-2-fill",
    "ri-anticlockwise-fill": "ri-anticlockwise-fill",
    "ri-app-store-fill": "ri-app-store-fill",
    "ri-apple-fill": "ri-apple-fill",
    "ri-apps-2-add-fill": "ri-apps-2-add-fill",
    "ri-apps-2-ai-fill": "ri-apps-2-ai-fill",
    "ri-apps-2-fill": "ri-apps-2-fill",
    "ri-apps-ai-fill": "ri-apps-ai-fill",
    "ri-apps-fill": "ri-apps-fill",
    "ri-archive-2-fill": "ri-archive-2-fill",
    "ri-archive-drawer-fill": "ri-archive-drawer-fill",
    "ri-archive-fill": "ri-archive-fill",
    "ri-archive-stack-fill": "ri-archive-stack-fill",
    "ri-area-chart-fill": "ri-area-chart-fill",
    "ri-armchair-fill": "ri-armchair-fill",
    "ri-arrow-down-box-fill": "ri-arrow-down-box-fill",
    "ri-arrow-down-circle-fill": "ri-arrow-down-circle-fill",
    "ri-arrow-down-double-fill": "ri-arrow-down-double-fill",
    "ri-arrow-down-fill": "ri-arrow-down-fill",
    "ri-arrow-down-long-fill": "ri-arrow-down-long-fill",
    "ri-arrow-down-s-fill": "ri-arrow-down-s-fill",
    "ri-arrow-down-wide-fill": "ri-arrow-down-wide-fill",
    "ri-arrow-drop-down-fill": "ri-arrow-drop-down-fill",
    "ri-arrow-drop-left-fill": "ri-arrow-drop-left-fill",
    "ri-arrow-drop-right-fill": "ri-arrow-drop-right-fill",
    "ri-arrow-drop-up-fill": "ri-arrow-drop-up-fill",
    "ri-arrow-go-back-fill": "ri-arrow-go-back-fill",
    "ri-arrow-go-forward-fill": "ri-arrow-go-forward-fill",
    "ri-arrow-left-box-fill": "ri-arrow-left-box-fill",
    "ri-arrow-left-circle-fill": "ri-arrow-left-circle-fill",
    "ri-arrow-left-double-fill": "ri-arrow-left-double-fill",
    "ri-arrow-left-down-box-fill": "ri-arrow-left-down-box-fill",
    "ri-arrow-left-down-fill": "ri-arrow-left-down-fill",
    "ri-arrow-left-down-long-fill": "ri-arrow-left-down-long-fill",
    "ri-arrow-left-fill": "ri-arrow-left-fill",
    "ri-arrow-left-long-fill": "ri-arrow-left-long-fill",
    "ri-arrow-left-right-fill": "ri-arrow-left-right-fill",
    "ri-arrow-left-s-fill": "ri-arrow-left-s-fill",
    "ri-arrow-left-up-box-fill": "ri-arrow-left-up-box-fill",
    "ri-arrow-left-up-fill": "ri-arrow-left-up-fill",
    "ri-arrow-left-up-long-fill": "ri-arrow-left-up-long-fill",
    "ri-arrow-left-wide-fill": "ri-arrow-left-wide-fill",
    "ri-arrow-right-box-fill": "ri-arrow-right-box-fill",
    "ri-arrow-right-circle-fill": "ri-arrow-right-circle-fill",
    "ri-arrow-right-double-fill": "ri-arrow-right-double-fill",
    "ri-arrow-right-down-box-fill": "ri-arrow-right-down-box-fill",
    "ri-arrow-right-down-fill": "ri-arrow-right-down-fill",
    "ri-arrow-right-down-long-fill": "ri-arrow-right-down-long-fill",
    "ri-arrow-right-fill": "ri-arrow-right-fill",
    "ri-arrow-right-long-fill": "ri-arrow-right-long-fill",
    "ri-arrow-right-s-fill": "ri-arrow-right-s-fill",
    "ri-arrow-right-up-box-fill": "ri-arrow-right-up-box-fill",
    "ri-arrow-right-up-fill": "ri-arrow-right-up-fill",
    "ri-arrow-right-up-long-fill": "ri-arrow-right-up-long-fill",
    "ri-arrow-right-wide-fill": "ri-arrow-right-wide-fill",
    "ri-arrow-turn-back-fill": "ri-arrow-turn-back-fill",
    "ri-arrow-turn-forward-fill": "ri-arrow-turn-forward-fill",
    "ri-arrow-up-box-fill": "ri-arrow-up-box-fill",
    "ri-arrow-up-circle-fill": "ri-arrow-up-circle-fill",
    "ri-arrow-up-double-fill": "ri-arrow-up-double-fill",
    "ri-arrow-up-down-fill": "ri-arrow-up-down-fill",
    "ri-arrow-up-fill": "ri-arrow-up-fill",
    "ri-arrow-up-long-fill": "ri-arrow-up-long-fill",
    "ri-arrow-up-s-fill": "ri-arrow-up-s-fill",
    "ri-arrow-up-wide-fill": "ri-arrow-up-wide-fill",
    "ri-artboard-2-fill": "ri-artboard-2-fill",
    "ri-artboard-fill": "ri-artboard-fill",
    "ri-article-fill": "ri-article-fill",
    "ri-aspect-ratio-fill": "ri-aspect-ratio-fill",
    "ri-at-fill": "ri-at-fill",
    "ri-atom-fill": "ri-atom-fill",
    "ri-attachment-fill": "ri-attachment-fill",
    "ri-auction-fill": "ri-auction-fill",
    "ri-award-fill": "ri-award-fill",
    "ri-baidu-fill": "ri-baidu-fill",
    "ri-ball-pen-fill": "ri-ball-pen-fill",
    "ri-bank-card-2-fill": "ri-bank-card-2-fill",
    "ri-bank-card-fill": "ri-bank-card-fill",
    "ri-bank-fill": "ri-bank-fill",
    "ri-bar-chart-2-fill": "ri-bar-chart-2-fill",
    "ri-bar-chart-box-ai-fill": "ri-bar-chart-box-ai-fill",
    "ri-bar-chart-box-fill": "ri-bar-chart-box-fill",
    "ri-bar-chart-fill": "ri-bar-chart-fill",
    "ri-bar-chart-grouped-fill": "ri-bar-chart-grouped-fill",
    "ri-bar-chart-horizontal-fill": "ri-bar-chart-horizontal-fill",
    "ri-barcode-box-fill": "ri-barcode-box-fill",
    "ri-barcode-fill": "ri-barcode-fill",
    "ri-bard-fill": "ri-bard-fill",
    "ri-barricade-fill": "ri-barricade-fill",
    "ri-base-station-fill": "ri-base-station-fill",
    "ri-baseball-fill": "ri-baseball-fill",
    "ri-basketball-fill": "ri-basketball-fill",
    "ri-battery-2-charge-fill": "ri-battery-2-charge-fill",
    "ri-battery-2-fill": "ri-battery-2-fill",
    "ri-battery-charge-fill": "ri-battery-charge-fill",
    "ri-battery-fill": "ri-battery-fill",
    "ri-battery-low-fill": "ri-battery-low-fill",
    "ri-battery-saver-fill": "ri-battery-saver-fill",
    "ri-battery-share-fill": "ri-battery-share-fill",
    "ri-bear-smile-fill": "ri-bear-smile-fill",
    "ri-beer-fill": "ri-beer-fill",
    "ri-behance-fill": "ri-behance-fill",
    "ri-bell-fill": "ri-bell-fill",
    "ri-bike-fill": "ri-bike-fill",
    "ri-bilibili-fill": "ri-bilibili-fill",
    "ri-bill-fill": "ri-bill-fill",
    "ri-billiards-fill": "ri-billiards-fill",
    "ri-binoculars-fill": "ri-binoculars-fill",
    "ri-bit-coin-fill": "ri-bit-coin-fill",
    "ri-blaze-fill": "ri-blaze-fill",
    "ri-blender-fill": "ri-blender-fill",
    "ri-blogger-fill": "ri-blogger-fill",
    "ri-bluesky-fill": "ri-bluesky-fill",
    "ri-bluetooth-connect-fill": "ri-bluetooth-connect-fill",
    "ri-bluetooth-fill": "ri-bluetooth-fill",
    "ri-blur-off-fill": "ri-blur-off-fill",
    "ri-bnb-fill": "ri-bnb-fill",
    "ri-body-scan-fill": "ri-body-scan-fill",
    "ri-book-2-fill": "ri-book-2-fill",
    "ri-book-3-fill": "ri-book-3-fill",
    "ri-book-ai-fill": "ri-book-ai-fill",
    "ri-book-fill": "ri-book-fill",
    "ri-book-marked-fill": "ri-book-marked-fill",
    "ri-book-open-fill": "ri-book-open-fill",
    "ri-book-read-fill": "ri-book-read-fill",
    "ri-book-shelf-fill": "ri-book-shelf-fill",
    "ri-booklet-fill": "ri-booklet-fill",
    "ri-bookmark-2-fill": "ri-bookmark-2-fill",
    "ri-bookmark-3-fill": "ri-bookmark-3-fill",
    "ri-bookmark-fill": "ri-bookmark-fill",
    "ri-bootstrap-fill": "ri-bootstrap-fill",
    "ri-bowl-fill": "ri-bowl-fill",
    "ri-box-1-fill": "ri-box-1-fill",
    "ri-box-2-fill": "ri-box-2-fill",
    "ri-box-3-fill": "ri-box-3-fill",
    "ri-boxing-fill": "ri-boxing-fill",
    "ri-braces-fill": "ri-braces-fill",
    "ri-brackets-fill": "ri-brackets-fill",
    "ri-brain-2-fill": "ri-brain-2-fill",
    "ri-brain-3-fill": "ri-brain-3-fill",
    "ri-brain-4-fill": "ri-brain-4-fill",
    "ri-brain-ai-3-fill": "ri-brain-ai-3-fill",
    "ri-brain-fill": "ri-brain-fill",
    "ri-bread-fill": "ri-bread-fill",
    "ri-briefcase-2-fill": "ri-briefcase-2-fill",
    "ri-briefcase-3-fill": "ri-briefcase-3-fill",
    "ri-briefcase-4-fill": "ri-briefcase-4-fill",
    "ri-briefcase-5-fill": "ri-briefcase-5-fill",
    "ri-briefcase-fill": "ri-briefcase-fill",
    "ri-broadcast-fill": "ri-broadcast-fill",
    "ri-brush-2-fill": "ri-brush-2-fill",
    "ri-brush-3-fill": "ri-brush-3-fill",
    "ri-brush-4-fill": "ri-brush-4-fill",
    "ri-brush-ai-3-fill": "ri-brush-ai-3-fill",
    "ri-brush-ai-fill": "ri-brush-ai-fill",
    "ri-brush-fill": "ri-brush-fill",
    "ri-btc-fill": "ri-btc-fill",
    "ri-bubble-chart-fill": "ri-bubble-chart-fill",
    "ri-bug-2-fill": "ri-bug-2-fill",
    "ri-bug-fill": "ri-bug-fill",
    "ri-building-2-fill": "ri-building-2-fill",
    "ri-building-3-fill": "ri-building-3-fill",
    "ri-building-4-fill": "ri-building-4-fill",
    "ri-building-fill": "ri-building-fill",
    "ri-bus-2-fill": "ri-bus-2-fill",
    "ri-bus-fill": "ri-bus-fill",
    "ri-bus-wifi-fill": "ri-bus-wifi-fill",
    "ri-cactus-fill": "ri-cactus-fill",
    "ri-cake-2-fill": "ri-cake-2-fill",
    "ri-cake-3-fill": "ri-cake-3-fill",
    "ri-cake-fill": "ri-cake-fill",
    "ri-calculator-fill": "ri-calculator-fill",
    "ri-calendar-2-fill": "ri-calendar-2-fill",
    "ri-calendar-check-fill": "ri-calendar-check-fill",
    "ri-calendar-close-fill": "ri-calendar-close-fill",
    "ri-calendar-event-fill": "ri-calendar-event-fill",
    "ri-calendar-fill": "ri-calendar-fill",
    "ri-calendar-schedule-fill": "ri-calendar-schedule-fill",
    "ri-calendar-todo-fill": "ri-calendar-todo-fill",
    "ri-camera-2-fill": "ri-camera-2-fill",
    "ri-camera-3-fill": "ri-camera-3-fill",
    "ri-camera-4-fill": "ri-camera-4-fill",
    "ri-camera-ai-2-fill": "ri-camera-ai-2-fill",
    "ri-camera-ai-fill": "ri-camera-ai-fill",
    "ri-camera-fill": "ri-camera-fill",
    "ri-camera-lens-ai-fill": "ri-camera-lens-ai-fill",
    "ri-camera-lens-fill": "ri-camera-lens-fill",
    "ri-camera-off-fill": "ri-camera-off-fill",
    "ri-camera-switch-fill": "ri-camera-switch-fill",
    "ri-candle-fill": "ri-candle-fill",
    "ri-capsule-fill": "ri-capsule-fill",
    "ri-car-fill": "ri-car-fill",
    "ri-car-washing-fill": "ri-car-washing-fill",
    "ri-caravan-fill": "ri-caravan-fill",
    "ri-cash-fill": "ri-cash-fill",
    "ri-cast-fill": "ri-cast-fill",
    "ri-cellphone-fill": "ri-cellphone-fill",
    "ri-celsius-fill": "ri-celsius-fill",
    "ri-centos-fill": "ri-centos-fill",
    "ri-certificate-2-fill": "ri-certificate-2-fill",
    "ri-certificate-fill": "ri-certificate-fill",
    "ri-character-recognition-fill": "ri-character-recognition-fill",
    "ri-charging-pile-2-fill": "ri-charging-pile-2-fill",
    "ri-charging-pile-fill": "ri-charging-pile-fill",
    "ri-chat-1-fill": "ri-chat-1-fill",
    "ri-chat-2-fill": "ri-chat-2-fill",
    "ri-chat-3-fill": "ri-chat-3-fill",
    "ri-chat-4-fill": "ri-chat-4-fill",
    "ri-chat-ai-2-fill": "ri-chat-ai-2-fill",
    "ri-chat-ai-3-fill": "ri-chat-ai-3-fill",
    "ri-chat-ai-4-fill": "ri-chat-ai-4-fill",
    "ri-chat-ai-fill": "ri-chat-ai-fill",
    "ri-chat-check-fill": "ri-chat-check-fill",
    "ri-chat-delete-fill": "ri-chat-delete-fill",
    "ri-chat-download-fill": "ri-chat-download-fill",
    "ri-chat-follow-up-fill": "ri-chat-follow-up-fill",
    "ri-chat-forward-fill": "ri-chat-forward-fill",
    "ri-chat-heart-fill": "ri-chat-heart-fill",
    "ri-chat-history-fill": "ri-chat-history-fill",
    "ri-chat-new-fill": "ri-chat-new-fill",
    "ri-chat-off-fill": "ri-chat-off-fill",
    "ri-chat-poll-fill": "ri-chat-poll-fill",
    "ri-chat-private-fill": "ri-chat-private-fill",
    "ri-chat-quote-fill": "ri-chat-quote-fill",
    "ri-chat-search-fill": "ri-chat-search-fill",
    "ri-chat-settings-fill": "ri-chat-settings-fill",
    "ri-chat-smile-2-fill": "ri-chat-smile-2-fill",
    "ri-chat-smile-3-fill": "ri-chat-smile-3-fill",
    "ri-chat-smile-ai-3-fill": "ri-chat-smile-ai-3-fill",
    "ri-chat-smile-ai-fill": "ri-chat-smile-ai-fill",
    "ri-chat-smile-fill": "ri-chat-smile-fill",
    "ri-chat-thread-fill": "ri-chat-thread-fill",
    "ri-chat-unread-fill": "ri-chat-unread-fill",
    "ri-chat-upload-fill": "ri-chat-upload-fill",
    "ri-chat-voice-ai-fill": "ri-chat-voice-ai-fill",
    "ri-chat-voice-fill": "ri-chat-voice-fill",
    "ri-check-double-fill": "ri-check-double-fill",
    "ri-check-fill": "ri-check-fill",
    "ri-checkbox-blank-circle-fill": "ri-checkbox-blank-circle-fill",
    "ri-checkbox-blank-fill": "ri-checkbox-blank-fill",
    "ri-checkbox-circle-fill": "ri-checkbox-circle-fill",
    "ri-checkbox-fill": "ri-checkbox-fill",
    "ri-checkbox-indeterminate-fill": "ri-checkbox-indeterminate-fill",
    "ri-checkbox-multiple-blank-fill": "ri-checkbox-multiple-blank-fill",
    "ri-checkbox-multiple-fill": "ri-checkbox-multiple-fill",
    "ri-chess-fill": "ri-chess-fill",
    "ri-china-railway-fill": "ri-china-railway-fill",
    "ri-chrome-fill": "ri-chrome-fill",
    "ri-circle-fill": "ri-circle-fill",
    "ri-clapperboard-ai-fill": "ri-clapperboard-ai-fill",
    "ri-clapperboard-fill": "ri-clapperboard-fill",
    "ri-claude-fill": "ri-claude-fill",
    "ri-clipboard-fill": "ri-clipboard-fill",
    "ri-clockwise-2-fill": "ri-clockwise-2-fill",
    "ri-clockwise-fill": "ri-clockwise-fill",
    "ri-close-circle-fill": "ri-close-circle-fill",
    "ri-close-fill": "ri-close-fill",
    "ri-close-large-fill": "ri-close-large-fill",
    "ri-closed-captioning-ai-fill": "ri-closed-captioning-ai-fill",
    "ri-closed-captioning-fill": "ri-closed-captioning-fill",
    "ri-cloud-fill": "ri-cloud-fill",
    "ri-cloud-off-fill": "ri-cloud-off-fill",
    "ri-cloud-windy-fill": "ri-cloud-windy-fill",
    "ri-cloudy-2-fill": "ri-cloudy-2-fill",
    "ri-cloudy-fill": "ri-cloudy-fill",
    "ri-code-ai-fill": "ri-code-ai-fill",
    "ri-code-box-fill": "ri-code-box-fill",
    "ri-code-fill": "ri-code-fill",
    "ri-code-s-fill": "ri-code-s-fill",
    "ri-code-s-slash-fill": "ri-code-s-slash-fill",
    "ri-codepen-fill": "ri-codepen-fill",
    "ri-coin-fill": "ri-coin-fill",
    "ri-coins-fill": "ri-coins-fill",
    "ri-collage-fill": "ri-collage-fill",
    "ri-collapse-diagonal-2-fill": "ri-collapse-diagonal-2-fill",
    "ri-collapse-diagonal-fill": "ri-collapse-diagonal-fill",
    "ri-collapse-horizontal-fill": "ri-collapse-horizontal-fill",
  }
});
styleForm.addInput('Couleur', 'point-symbol-color', new InputColor());
styleForm.addBreak('point-symbol');

styleForm.addInput('Intérieur', 'fill-color', new InputColor());
styleForm.addBreak('fill-style');

styleForm.addInput('Ligne', 'stroke-color', new InputColor());
styleForm.addCustomSelect({
  label: 'Bordure',
  property: 'stroke-line-dash',
  options: {
    "": "Continue",
    "5,5": "Tiret",
    "0,5": "Pointillé",
    "10,5,0,5": "Tirets irréguliers",
  },
  type: "dash",
});
styleForm.addCustomInput({
  label: 'Taille',
  property: 'stroke-width',
});

styleForm.addBreak('line-arrow');
styleForm.addCustomSelect({
  label: 'Début',
  disabled: true,
  property: 'line-arrow-start',
  options: {
    "": "Simple",
    "triangle": "Flèche",
    "circle": "Rond",
    "square": "Carré",
  },
  type: "arrow",
});

styleForm.addCustomSelect({
  label: 'Fin',
  property: 'line-arrow-end',
  options: {
    "": "Simple",
    "triangle": "Flèche",
    "circle": "Rond",
    "square": "Carré",
  },
  type: "arrow",
});

// Création du Dialog avec navigation tertiaire
const styleDialog = new Dialog({
  id: "style-dialog",
  title: "Dialog",
  position: "left",
  items: [
    {
      label: "Style",
      content: styleForm.getContent(),
      onOpen: (...args) => console.log(...args),
      title: "Configuration du style"
    },
    {
      label: "Texte",
      content: "<p>Onglet Texte</p>",
      title: "Configuration du texte"
    },
    {
      label: "Infobulle",
      content: "<p>Onglet Infobulle</p>",
      title: "Configuration de l'infobulle"
    },
    {
      label: "Attributs",
      content: "<p>Onglet Attributs</p>",
      title: "Configuration des attributs"
    }
  ],
  labelTabNav: "Navigation de configuration",

});

export default styleDialog;
export { styleForm };