---
name: 🚀 Spécifier une évolution
description: Renseigner les informations nécessaires pour créer ou améliorer une fonctionnalité pour cartes.gouv.fr
labels:
  - enhancement
body:
  - type: textarea
    id: job-to-be-done
    attributes:
      label: 📝 Job to be done (JTBD)
      description: |
        Décrivez la tâche générique que l'utilisateur cherche à accomplir, indépendamment de l'outil.
      placeholder: |
        exemple : Représenter mes données publiques sur une carte pour identifier des zones sous-dotées et ajuster la planification
  - type: textarea
    id: user-story
    attributes:
      label: 🎯 User Story
      description: |
        Décrivez précisément le comportement de la nouvelle fonctionnalité.
      placeholder: |
        - En tant que [type d'utilisateur / persona]
        - Je veux [action concrète à réaliser]
        - Afin de [valeur attendue / bénéfice]
    validations:
      required: true
  - type: textarea
    id: design
    attributes:
      label: 🎨 Design
      description: |
        Décrivez les éléments de design nécéssaire au développement de la fonctionnalité.
      placeholder: |
        - Composition
        - Comportement
        - Contenus
        - Emplacement
        - Points de rupture
  - type: textarea
    id: criteres-d-acceptation
    attributes:
      label: ✅ Critères d'acceptation
      description: >
        Décrivez les conditions observables qui permettent d'identifier la bonne mise en place de l'US.
      placeholder: |
        - [ ] Exemple : Importe de fichiers CSV/Excel possible
        - [ ] Exemple : Les points apparaissent correctement sur la carte
        - [ ] Exemple : Le message d'erreur s'affiche si format non conforme
    validations:
      required: true
  - type: textarea
    id: liens
    attributes:
      label: 🔗 Liens
      description: |
        Renseignez les liens utiles à l'évolution.
      placeholder: |
        - Maquette figma : [lien]
        - Données de test : [lien]
        - Documentation annexe : [lien]
  - type: textarea
    id: impact-attendu
    attributes:
      label: 📊 impact attendu
      description: >
        Décrivez quelle valeur cela apporte-t-il à l'utilisateur, et
        comment le mesurer.
      placeholder: >
        - Valeur utilisateur : [Exemple : Faciliter la décision => l'agent gagne du temps et fiabilise ses analyses]
        - Mesure : [Exemple : % d'imports réussis sans erreur, temps moyen de traitement gagné]
  - type: textarea
    id: additional-context
    attributes:
      label: 🔧 Autres éléments de contexte
      description: |
        À remplir par l'équipe technique pour s'assurer que l'US est réalisable.
