/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import { apiURL } from "../../env";

import type {
  BadRequestResponse,
  ForbiddenResponse,
  GetUsers200Item,
  GetUsersParams,
  InvalidResponse,
  NotConnectedResponse,
  NotFoundResponse,
  UserMeEdit,
  UserPublic,
  UserView,
} from "../model";

import { fetchWithAuth } from ".././fetchWithAuth";

export type getMeResponse200 = {
  data: UserView;
  status: 200;
};

export type getMeResponse401 = {
  data: NotConnectedResponse;
  status: 401;
};

export type getMeResponseSuccess = getMeResponse200 & {
  headers: Headers;
};
export type getMeResponseError = getMeResponse401 & {
  headers: Headers;
};

export type getMeResponse = getMeResponseSuccess | getMeResponseError;

export const getGetMeUrl = () => {
  return `${apiURL}/api/me`;
};

export const getMe = async (
  options?: Parameters<typeof fetchWithAuth>[1],
): Promise<getMeResponse> => {
  return fetchWithAuth<getMeResponse>(getGetMeUrl(), {
    ...options,
    method: "GET",
  });
};

export type deleteMeResponse204 = {
  data: void;
  status: 204;
};

export type deleteMeResponse401 = {
  data: NotConnectedResponse;
  status: 401;
};

export type deleteMeResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type deleteMeResponse451 = {
  data: InvalidResponse;
  status: 451;
};

export type deleteMeResponseSuccess = deleteMeResponse204 & {
  headers: Headers;
};
export type deleteMeResponseError = (
  deleteMeResponse401 | deleteMeResponse403 | deleteMeResponse451
) & {
  headers: Headers;
};

export type deleteMeResponse = deleteMeResponseSuccess | deleteMeResponseError;

export const getDeleteMeUrl = () => {
  return `${apiURL}/api/me`;
};

/**
 * Supprime en douceur (https://phpreaction.com/support/suppression-en-douceur-soft-delete/) le compte de l'utilisateur connecté
 */
export const deleteMe = async (
  options?: Parameters<typeof fetchWithAuth>[1],
): Promise<deleteMeResponse> => {
  return fetchWithAuth<deleteMeResponse>(getDeleteMeUrl(), {
    ...options,
    method: "DELETE",
  });
};

export type patchMeResponse200 = {
  data: UserView;
  status: 200;
};

export type patchMeResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type patchMeResponse401 = {
  data: NotConnectedResponse;
  status: 401;
};

export type patchMeResponseSuccess = patchMeResponse200 & {
  headers: Headers;
};
export type patchMeResponseError = (patchMeResponse400 | patchMeResponse401) & {
  headers: Headers;
};

export type patchMeResponse = patchMeResponseSuccess | patchMeResponseError;

export const getPatchMeUrl = () => {
  return `${apiURL}/api/me`;
};

/**
 * Le paramètre **current_password** est nécessaire pour modifier les paramètres username, email et new_password
 * username, email et public_name sont uniques, la réponse 400 '... already used' peut être renvoyée
 */
export const patchMe = async (
  userMeEdit: UserMeEdit,
  options?: Parameters<typeof fetchWithAuth>[1],
): Promise<patchMeResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return fetchWithAuth<patchMeResponse>(getPatchMeUrl(), {
    ...options,
    method: "PATCH",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(userMeEdit),
  });
};

export type getUserByPublicidResponse200 = {
  data: UserPublic;
  status: 200;
};

export type getUserByPublicidResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getUserByPublicidResponseSuccess = getUserByPublicidResponse200 & {
  headers: Headers;
};
export type getUserByPublicidResponseError = getUserByPublicidResponse404 & {
  headers: Headers;
};

export type getUserByPublicidResponse =
  getUserByPublicidResponseSuccess | getUserByPublicidResponseError;

export const getGetUserByPublicidUrl = (publicId: string) => {
  return `${apiURL}/api/users/public/${publicId}`;
};

export const getUserByPublicid = async (
  publicId: string,
  options?: Parameters<typeof fetchWithAuth>[1],
): Promise<getUserByPublicidResponse> => {
  return fetchWithAuth<getUserByPublicidResponse>(
    getGetUserByPublicidUrl(publicId),
    {
      ...options,
      method: "GET",
    },
  );
};

export type getUsersResponse200 = {
  data: GetUsers200Item[];
  status: 200;
};

export type getUsersResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type getUsersResponseSuccess = getUsersResponse200 & {
  headers: Headers;
};
export type getUsersResponseError = getUsersResponse400 & {
  headers: Headers;
};

export type getUsersResponse = getUsersResponseSuccess | getUsersResponseError;

export const getGetUsersUrl = (params: GetUsersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `${apiURL}/api/users?${stringifiedParams}`
    : `${apiURL}/api/users`;
};

/**
 * Recherche d'utilisateurs par autocompletion
 */
export const getUsers = async (
  params: GetUsersParams,
  options?: Parameters<typeof fetchWithAuth>[1],
): Promise<getUsersResponse> => {
  return fetchWithAuth<getUsersResponse>(getGetUsersUrl(params), {
    ...options,
    method: "GET",
  });
};
