/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import { apiURL } from "../../env";

import type { Notification } from "../model";

import { fetchWithAuth } from ".././fetchWithAuth.ts";

export type getNotificationsResponse200 = {
    data: Notification[];
    status: 200;
};

export type getNotificationsResponseSuccess = getNotificationsResponse200 & {
    headers: Headers;
};
export type getNotificationsResponse = getNotificationsResponseSuccess;

export const getGetNotificationsUrl = () => {
    return `${apiURL}/api/notifications`;
};

export const getNotifications = async (options?: Parameters<typeof fetchWithAuth>[1]): Promise<getNotificationsResponse> => {
    return fetchWithAuth<getNotificationsResponse>(getGetNotificationsUrl(), {
        ...options,
        method: "GET",
    });
};
