/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import { apiURL } from "../../env";

import type {
    BadRequestResponse,
    DeletedResponse,
    ForbiddenResponse,
    GetMapsParams,
    GetMapsUsersParams,
    InvalidResponse,
    MapResearch,
    MapView,
    NotConnectedResponse,
    NotFoundResponse,
    PatchMapByEditIdBody,
    PostMapBody,
    PostMapFileByEditIdBody,
} from "../model";

import { fetchWithAuth } from ".././fetchWithAuth.js";

export type getMapsResponse200 = {
    data: MapResearch;
    status: 200;
};

export type getMapsResponse206 = {
    data: MapResearch;
    status: 206;
};

export type getMapsResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type getMapsResponse403 = {
    data: ForbiddenResponse;
    status: 403;
};

export type getMapsResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type getMapsResponseSuccess = (getMapsResponse200 | getMapsResponse206) & {
    headers: Headers;
};
export type getMapsResponseError = (getMapsResponse401 | getMapsResponse403 | getMapsResponse404) & {
    headers: Headers;
};

export type getMapsResponse = getMapsResponseSuccess | getMapsResponseError;

export const getGetMapsUrl = (params?: GetMapsParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : String(value));
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0 ? `${apiURL}/api/maps?${stringifiedParams}` : `${apiURL}/api/maps`;
};

export const getMaps = async (params?: GetMapsParams, options?: Parameters<typeof fetchWithAuth>[1]): Promise<getMapsResponse> => {
    return fetchWithAuth<getMapsResponse>(getGetMapsUrl(params), {
        ...options,
        method: "GET",
    });
};

export type postMapResponse201 = {
    data: MapView;
    status: 201;
};

export type postMapResponse400 = {
    data: BadRequestResponse;
    status: 400;
};

export type postMapResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type postMapResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type postMapResponseSuccess = postMapResponse201 & {
    headers: Headers;
};
export type postMapResponseError = (postMapResponse400 | postMapResponse401 | postMapResponse404) & {
    headers: Headers;
};

export type postMapResponse = postMapResponseSuccess | postMapResponseError;

export const getPostMapUrl = () => {
    return `${apiURL}/api/maps`;
};

export const postMap = async (postMapBody: PostMapBody, options?: Parameters<typeof fetchWithAuth>[1]): Promise<postMapResponse> => {
    const formData = new FormData();
    formData.append(`carte`, JSON.stringify(postMapBody.carte));
    formData.append(`file`, postMapBody.file);

    return fetchWithAuth<postMapResponse>(getPostMapUrl(), {
        ...options,
        method: "POST",
        body: formData,
    });
};

export type getMapsUsersResponse200 = {
    data: string[];
    status: 200;
};

export type getMapsUsersResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type getMapsUsersResponseSuccess = getMapsUsersResponse200 & {
    headers: Headers;
};
export type getMapsUsersResponseError = getMapsUsersResponse404 & {
    headers: Headers;
};

export type getMapsUsersResponse = getMapsUsersResponseSuccess | getMapsUsersResponseError;

export const getGetMapsUsersUrl = (params?: GetMapsUsersParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : String(value));
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0 ? `${apiURL}/api/maps/users?${stringifiedParams}` : `${apiURL}/api/maps/users`;
};

/**
 * Autocompletion des utilisateurs ayant des cartes publiques correspondant aux critères de recherche
 */
export const getMapsUsers = async (params?: GetMapsUsersParams, options?: Parameters<typeof fetchWithAuth>[1]): Promise<getMapsUsersResponse> => {
    return fetchWithAuth<getMapsUsersResponse>(getGetMapsUsersUrl(params), {
        ...options,
        method: "GET",
    });
};

export type getMapByViewIdResponse200 = {
    data: MapView;
    status: 200;
};

export type getMapByViewIdResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type getMapByViewIdResponse451 = {
    data: InvalidResponse;
    status: 451;
};

export type getMapByViewIdResponseSuccess = getMapByViewIdResponse200 & {
    headers: Headers;
};
export type getMapByViewIdResponseError = (getMapByViewIdResponse404 | getMapByViewIdResponse451) & {
    headers: Headers;
};

export type getMapByViewIdResponse = getMapByViewIdResponseSuccess | getMapByViewIdResponseError;

export const getGetMapByViewIdUrl = (viewId: number | string) => {
    return `${apiURL}/api/maps/${viewId}`;
};

/**
 * Récupérer les metadata de la carte par son identifiant de visualisation
 */
export const getMapByViewId = async (viewId: number | string, options?: Parameters<typeof fetchWithAuth>[1]): Promise<getMapByViewIdResponse> => {
    return fetchWithAuth<getMapByViewIdResponse>(getGetMapByViewIdUrl(viewId), {
        ...options,
        method: "GET",
    });
};

export type getMapEditByEditIdResponse200 = {
    data: MapView;
    status: 200;
};

export type getMapEditByEditIdResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type getMapEditByEditIdResponse451 = {
    data: InvalidResponse;
    status: 451;
};

export type getMapEditByEditIdResponseSuccess = getMapEditByEditIdResponse200 & {
    headers: Headers;
};
export type getMapEditByEditIdResponseError = (getMapEditByEditIdResponse404 | getMapEditByEditIdResponse451) & {
    headers: Headers;
};

export type getMapEditByEditIdResponse = getMapEditByEditIdResponseSuccess | getMapEditByEditIdResponseError;

export const getGetMapEditByEditIdUrl = (editId: number | string) => {
    return `${apiURL}/api/maps/${editId}/edit`;
};

/**
 * Récupérer les metadata de la carte par son identifiant d'édition
 */
export const getMapEditByEditId = async (editId: number | string, options?: Parameters<typeof fetchWithAuth>[1]): Promise<getMapEditByEditIdResponse> => {
    return fetchWithAuth<getMapEditByEditIdResponse>(getGetMapEditByEditIdUrl(editId), {
        ...options,
        method: "GET",
    });
};

export type getMapFileByViewIdResponse200 = {
    data: unknown;
    status: 200;
};

export type getMapFileByViewIdResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type getMapFileByViewIdResponse451 = {
    data: InvalidResponse;
    status: 451;
};

export type getMapFileByViewIdResponseSuccess = getMapFileByViewIdResponse200 & {
    headers: Headers;
};
export type getMapFileByViewIdResponseError = (getMapFileByViewIdResponse404 | getMapFileByViewIdResponse451) & {
    headers: Headers;
};

export type getMapFileByViewIdResponse = getMapFileByViewIdResponseSuccess | getMapFileByViewIdResponseError;

export const getGetMapFileByViewIdUrl = (viewId: number | string) => {
    return `${apiURL}/api/maps/${viewId}/file`;
};

/**
 * Récupérer les data de la carte par son identifiant de visualisation
 */
export const getMapFileByViewId = async (viewId: number | string, options?: Parameters<typeof fetchWithAuth>[1]): Promise<getMapFileByViewIdResponse> => {
    return fetchWithAuth<getMapFileByViewIdResponse>(getGetMapFileByViewIdUrl(viewId), {
        ...options,
        method: "GET",
    });
};

export type getMapFileByEditIdResponse200 = {
    data: unknown;
    status: 200;
};

export type getMapFileByEditIdResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type getMapFileByEditIdResponse451 = {
    data: InvalidResponse;
    status: 451;
};

export type getMapFileByEditIdResponseSuccess = getMapFileByEditIdResponse200 & {
    headers: Headers;
};
export type getMapFileByEditIdResponseError = (getMapFileByEditIdResponse404 | getMapFileByEditIdResponse451) & {
    headers: Headers;
};

export type getMapFileByEditIdResponse = getMapFileByEditIdResponseSuccess | getMapFileByEditIdResponseError;

export const getGetMapFileByEditIdUrl = (editId: number | string) => {
    return `${apiURL}/api/maps/${editId}/edit/file`;
};

/**
 * Récupérer les data de la carte par son identifiant d'édition
 */
export const getMapFileByEditId = async (editId: number | string, options?: Parameters<typeof fetchWithAuth>[1]): Promise<getMapFileByEditIdResponse> => {
    return fetchWithAuth<getMapFileByEditIdResponse>(getGetMapFileByEditIdUrl(editId), {
        ...options,
        method: "GET",
    });
};

export type deleteMapByEditIdResponse204 = {
    data: DeletedResponse;
    status: 204;
};

export type deleteMapByEditIdResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type deleteMapByEditIdResponse403 = {
    data: ForbiddenResponse;
    status: 403;
};

export type deleteMapByEditIdResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type deleteMapByEditIdResponseSuccess = deleteMapByEditIdResponse204 & {
    headers: Headers;
};
export type deleteMapByEditIdResponseError = (deleteMapByEditIdResponse401 | deleteMapByEditIdResponse403 | deleteMapByEditIdResponse404) & {
    headers: Headers;
};

export type deleteMapByEditIdResponse = deleteMapByEditIdResponseSuccess | deleteMapByEditIdResponseError;

export const getDeleteMapByEditIdUrl = (editId: number | string) => {
    return `${apiURL}/api/maps/${editId}`;
};

export const deleteMapByEditId = async (editId: number | string, options?: Parameters<typeof fetchWithAuth>[1]): Promise<deleteMapByEditIdResponse> => {
    return fetchWithAuth<deleteMapByEditIdResponse>(getDeleteMapByEditIdUrl(editId), {
        ...options,
        method: "DELETE",
    });
};

export type patchMapByEditIdResponse200 = {
    data: MapView;
    status: 200;
};

export type patchMapByEditIdResponse400 = {
    data: BadRequestResponse;
    status: 400;
};

export type patchMapByEditIdResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type patchMapByEditIdResponse403 = {
    data: ForbiddenResponse;
    status: 403;
};

export type patchMapByEditIdResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type patchMapByEditIdResponseSuccess = patchMapByEditIdResponse200 & {
    headers: Headers;
};
export type patchMapByEditIdResponseError = (
    patchMapByEditIdResponse400 | patchMapByEditIdResponse401 | patchMapByEditIdResponse403 | patchMapByEditIdResponse404
) & {
    headers: Headers;
};

export type patchMapByEditIdResponse = patchMapByEditIdResponseSuccess | patchMapByEditIdResponseError;

export const getPatchMapByEditIdUrl = (editId: number | string) => {
    return `${apiURL}/api/maps/${editId}`;
};

export const patchMapByEditId = async (
    editId: number | string,
    patchMapByEditIdBody: PatchMapByEditIdBody,
    options?: Parameters<typeof fetchWithAuth>[1]
): Promise<patchMapByEditIdResponse> => {
    const getHeaders = (h?: NonNullable<RequestInit["headers"]>): Record<string, string | readonly string[]> => {
        if (!h) return {};
        if (h instanceof Headers) return Object.fromEntries(h.entries());
        if (Symbol.iterator in h) {
            return Object.fromEntries(Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]));
        }
        const headers: Record<string, string | readonly string[]> = {};
        for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
            if (value !== undefined) headers[name] = value;
        }
        return headers;
    };
    return fetchWithAuth<patchMapByEditIdResponse>(getPatchMapByEditIdUrl(editId), {
        ...options,
        method: "PATCH",
        headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
        body: JSON.stringify(patchMapByEditIdBody),
    });
};

export type postMapFileByEditIdResponse200 = {
    data: void;
    status: 200;
};

export type postMapFileByEditIdResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type postMapFileByEditIdResponseSuccess = postMapFileByEditIdResponse200 & {
    headers: Headers;
};
export type postMapFileByEditIdResponseError = postMapFileByEditIdResponse404 & {
    headers: Headers;
};

export type postMapFileByEditIdResponse = postMapFileByEditIdResponseSuccess | postMapFileByEditIdResponseError;

export const getPostMapFileByEditIdUrl = (editId: number | string) => {
    return `${apiURL}/api/maps/${editId}/file`;
};

export const postMapFileByEditId = async (
    editId: number | string,
    postMapFileByEditIdBody: PostMapFileByEditIdBody,
    options?: Parameters<typeof fetchWithAuth>[1]
): Promise<postMapFileByEditIdResponse> => {
    const formData = new FormData();
    formData.append(`file`, postMapFileByEditIdBody.file);

    return fetchWithAuth<postMapFileByEditIdResponse>(getPostMapFileByEditIdUrl(editId), {
        ...options,
        method: "POST",
        body: formData,
    });
};
