/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import { apiURL } from "../../env";

import type {
    BadRequestResponse,
    DeletedResponse,
    ForbiddenResponse,
    GetUserMediaFoldersParams,
    GetUserMediasParams,
    InvalidResponse,
    Media,
    MediaList,
    NotConnectedResponse,
    NotFoundResponse,
    PostMediaBody,
    PostMediaFileById200,
    PostMediaFileByIdBody,
    PutMediaAttribute200,
    PutMediaAttributeBody,
    TooLargeResponse,
} from "../model";

import { fetchWithAuth } from ".././fetchWithAuth.ts";

export type getUserMediasResponse200 = {
    data: MediaList;
    status: 200;
};

export type getUserMediasResponse206 = {
    data: MediaList;
    status: 206;
};

export type getUserMediasResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type getUserMediasResponse403 = {
    data: ForbiddenResponse;
    status: 403;
};

export type getUserMediasResponseSuccess = (getUserMediasResponse200 | getUserMediasResponse206) & {
    headers: Headers;
};
export type getUserMediasResponseError = (getUserMediasResponse401 | getUserMediasResponse403) & {
    headers: Headers;
};

export type getUserMediasResponse = getUserMediasResponseSuccess | getUserMediasResponseError;

export const getGetUserMediasUrl = (params?: GetUserMediasParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : String(value));
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0 ? `${apiURL}/api/medias?${stringifiedParams}` : `${apiURL}/api/medias`;
};

/**
 * Renvoie les medias de l'utilisateur connecté
 */
export const getUserMedias = async (params?: GetUserMediasParams, options?: Parameters<typeof fetchWithAuth>[1]): Promise<getUserMediasResponse> => {
    return fetchWithAuth<getUserMediasResponse>(getGetUserMediasUrl(params), {
        ...options,
        method: "GET",
    });
};

export type postMediaResponse201 = {
    data: Media;
    status: 201;
};

export type postMediaResponse400 = {
    data: BadRequestResponse;
    status: 400;
};

export type postMediaResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type postMediaResponse403 = {
    data: ForbiddenResponse;
    status: 403;
};

export type postMediaResponse413 = {
    data: TooLargeResponse;
    status: 413;
};

export type postMediaResponseSuccess = postMediaResponse201 & {
    headers: Headers;
};
export type postMediaResponseError = (postMediaResponse400 | postMediaResponse401 | postMediaResponse403 | postMediaResponse413) & {
    headers: Headers;
};

export type postMediaResponse = postMediaResponseSuccess | postMediaResponseError;

export const getPostMediaUrl = () => {
    return `${apiURL}/api/medias`;
};

/**
 * Ajoute un media à l'utilisateur connecté ou à l'organisation d'identifiant organization_id si renseigné
 */
export const postMedia = async (postMediaBody: PostMediaBody, options?: Parameters<typeof fetchWithAuth>[1]): Promise<postMediaResponse> => {
    const formData = new FormData();
    formData.append(`file`, postMediaBody.file);
    if (postMediaBody.folder !== undefined) {
        formData.append(`folder`, postMediaBody.folder);
    }
    if (postMediaBody.name !== undefined) {
        formData.append(`name`, postMediaBody.name);
    }
    if (postMediaBody.organization_id !== undefined && postMediaBody.organization_id !== null) {
        formData.append(`organization_id`, postMediaBody.organization_id);
    }

    return fetchWithAuth<postMediaResponse>(getPostMediaUrl(), {
        ...options,
        method: "POST",
        body: formData,
    });
};

export type getUserMediaFoldersResponse200 = {
    data: string[];
    status: 200;
};

export type getUserMediaFoldersResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type getUserMediaFoldersResponseSuccess = getUserMediaFoldersResponse200 & {
    headers: Headers;
};
export type getUserMediaFoldersResponseError = getUserMediaFoldersResponse401 & {
    headers: Headers;
};

export type getUserMediaFoldersResponse = getUserMediaFoldersResponseSuccess | getUserMediaFoldersResponseError;

export const getGetUserMediaFoldersUrl = (params?: GetUserMediaFoldersParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : String(value));
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0 ? `${apiURL}/api/medias/folders?${stringifiedParams}` : `${apiURL}/api/medias/folders`;
};

/**
 * Renvoie les dossiers d'images de l'utilisateur
 */
export const getUserMediaFolders = async (
    params?: GetUserMediaFoldersParams,
    options?: Parameters<typeof fetchWithAuth>[1]
): Promise<getUserMediaFoldersResponse> => {
    return fetchWithAuth<getUserMediaFoldersResponse>(getGetUserMediaFoldersUrl(params), {
        ...options,
        method: "GET",
    });
};

export type getImageByFilenameResponse200 = {
    data: void;
    status: 200;
};

export type getImageByFilenameResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type getImageByFilenameResponse451 = {
    data: InvalidResponse;
    status: 451;
};

export type getImageByFilenameResponseSuccess = getImageByFilenameResponse200 & {
    headers: Headers;
};
export type getImageByFilenameResponseError = (getImageByFilenameResponse404 | getImageByFilenameResponse451) & {
    headers: Headers;
};

export type getImageByFilenameResponse = getImageByFilenameResponseSuccess | getImageByFilenameResponseError;

export const getGetImageByFilenameUrl = (filename: string) => {
    return `${apiURL}/api/image/${filename}`;
};

/**
 * Renvoie l'image au format binaire, l'extension n'est pas prise en compte (ex : abc1234).
 * Préfixer le filename par 'thumb_' pour recevoir la miniature (200px sur la plus grande dimension).
 */
export const getImageByFilename = async (filename: string, options?: Parameters<typeof fetchWithAuth>[1]): Promise<getImageByFilenameResponse> => {
    return fetchWithAuth<getImageByFilenameResponse>(getGetImageByFilenameUrl(filename), {
        ...options,
        method: "GET",
    });
};

export type deleteMediaByIdResponse204 = {
    data: DeletedResponse;
    status: 204;
};

export type deleteMediaByIdResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type deleteMediaByIdResponse403 = {
    data: ForbiddenResponse;
    status: 403;
};

export type deleteMediaByIdResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type deleteMediaByIdResponse451 = {
    data: InvalidResponse;
    status: 451;
};

export type deleteMediaByIdResponseSuccess = deleteMediaByIdResponse204 & {
    headers: Headers;
};
export type deleteMediaByIdResponseError = (
    deleteMediaByIdResponse401 | deleteMediaByIdResponse403 | deleteMediaByIdResponse404 | deleteMediaByIdResponse451
) & {
    headers: Headers;
};

export type deleteMediaByIdResponse = deleteMediaByIdResponseSuccess | deleteMediaByIdResponseError;

export const getDeleteMediaByIdUrl = (id: number | string) => {
    return `${apiURL}/api/medias/${id}`;
};

/**
 * Supprime un media de l'utilisateur connecté. Un média non valide ne peut pas être supprimé
 */
export const deleteMediaById = async (id: number | string, options?: Parameters<typeof fetchWithAuth>[1]): Promise<deleteMediaByIdResponse> => {
    return fetchWithAuth<deleteMediaByIdResponse>(getDeleteMediaByIdUrl(id), {
        ...options,
        method: "DELETE",
    });
};

export type putMediaAttributeResponse200 = {
    data: PutMediaAttribute200;
    status: 200;
};

export type putMediaAttributeResponse400 = {
    data: BadRequestResponse;
    status: 400;
};

export type putMediaAttributeResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type putMediaAttributeResponse403 = {
    data: ForbiddenResponse;
    status: 403;
};

export type putMediaAttributeResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type putMediaAttributeResponseSuccess = putMediaAttributeResponse200 & {
    headers: Headers;
};
export type putMediaAttributeResponseError = (
    putMediaAttributeResponse400 | putMediaAttributeResponse401 | putMediaAttributeResponse403 | putMediaAttributeResponse404
) & {
    headers: Headers;
};

export type putMediaAttributeResponse = putMediaAttributeResponseSuccess | putMediaAttributeResponseError;

export const getPutMediaAttributeUrl = (id: number | string, attribute: string) => {
    return `${apiURL}/api/medias/${id}/${attribute}`;
};

/**
 * Affecte value à l'attribut du media d'identifiant id (attribute dans ['folder', 'name'])
 */
export const putMediaAttribute = async (
    id: number | string,
    attribute: string,
    putMediaAttributeBody: PutMediaAttributeBody,
    options?: Parameters<typeof fetchWithAuth>[1]
): Promise<putMediaAttributeResponse> => {
    const getHeaders = (h?: NonNullable<RequestInit["headers"]>): Record<string, string | readonly string[]> => {
        if (!h) return {};
        if (h instanceof Headers) return Object.fromEntries(h.entries());
        if (Symbol.iterator in h) {
            return Object.fromEntries(Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]));
        }
        const headers: Record<string, string | readonly string[]> = {};
        for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
            if (value !== undefined) headers[name] = value;
        }
        return headers;
    };
    return fetchWithAuth<putMediaAttributeResponse>(getPutMediaAttributeUrl(id, attribute), {
        ...options,
        method: "PUT",
        headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
        body: JSON.stringify(putMediaAttributeBody),
    });
};

export type postMediaFileByIdResponse200 = {
    data: PostMediaFileById200;
    status: 200;
};

export type postMediaFileByIdResponse400 = {
    data: BadRequestResponse;
    status: 400;
};

export type postMediaFileByIdResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type postMediaFileByIdResponse403 = {
    data: ForbiddenResponse;
    status: 403;
};

export type postMediaFileByIdResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type postMediaFileByIdResponse413 = {
    data: TooLargeResponse;
    status: 413;
};

export type postMediaFileByIdResponseSuccess = postMediaFileByIdResponse200 & {
    headers: Headers;
};
export type postMediaFileByIdResponseError = (
    postMediaFileByIdResponse400 | postMediaFileByIdResponse401 | postMediaFileByIdResponse403 | postMediaFileByIdResponse404 | postMediaFileByIdResponse413
) & {
    headers: Headers;
};

export type postMediaFileByIdResponse = postMediaFileByIdResponseSuccess | postMediaFileByIdResponseError;

export const getPostMediaFileByIdUrl = (id: number | string) => {
    return `${apiURL}/api/medias/${id}/file`;
};

/**
 * Modifie l'image associée au media
 */
export const postMediaFileById = async (
    id: number | string,
    postMediaFileByIdBody: PostMediaFileByIdBody,
    options?: Parameters<typeof fetchWithAuth>[1]
): Promise<postMediaFileByIdResponse> => {
    const formData = new FormData();
    formData.append(`file`, postMediaFileByIdBody.file);

    return fetchWithAuth<postMediaFileByIdResponse>(getPostMediaFileByIdUrl(id), {
        ...options,
        method: "POST",
        body: formData,
    });
};
