/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import type { MapResearchActivesItem } from "./mapResearchActivesItem.ts";
import type { MapResearchItem } from "./mapResearchItem.ts";
import type { MapResearchOrganization } from "./mapResearchOrganization.ts";
import type { MapResearchPremiumsItem } from "./mapResearchPremiumsItem.ts";
import type { MapResearchSharesItem } from "./mapResearchSharesItem.ts";
import type { MapResearchTheme } from "./mapResearchTheme.ts";
import type { MapResearchTypesItem } from "./mapResearchTypesItem.ts";
import type { MapResearchUsersItem } from "./mapResearchUsersItem.ts";
import type { MapResearchValidesItem } from "./mapResearchValidesItem.ts";

/**
 * Recherche des cartes
 */
export interface MapResearch {
    maps: MapResearchItem[];
    themes: MapResearchTheme[];
    organizations: MapResearchOrganization[];
    users: MapResearchUsersItem[];
    types: MapResearchTypesItem[];
    premiums: MapResearchPremiumsItem[];
    actives: MapResearchActivesItem[];
    valides: MapResearchValidesItem[];
    shares: MapResearchSharesItem[];
    /** Mot(s) contenu(s) dans le titre, la description ou le theme des cartes */
    query: string;
    /** Nombre de cartes correspondant à la recherche */
    count: number;
    /**
     * Nombre de cartes reçues dans la requête. Peut être null lorsque toutes les cartes sont demandées.
     * @nullable
     */
    limit: number | null;
    /** Nombre de cartes à passer avant de les inclure dans la requete */
    offset: number;
}
