/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import { apiURL } from "../../env";

import type {
  AddMemberToOrganization200,
  AddMemberToOrganizationBody,
  BadRequestResponse,
  DeletedResponse,
  ForbiddenResponse,
  GetOrganizationLinksById200,
  GetOrganizationsMe200Item,
  GetOrganizationsRoles200Item,
  NotConnectedResponse,
  NotFoundResponse,
  Organization,
  PostOrganizationBody,
  PutOrganizationAttribute200,
  PutOrganizationAttributeBody,
  PutOrganizationJoinLinkRole200,
  PutOrganizationJoinLinkRoleBody,
  PutOrganizationMemberRole200,
  PutOrganizationMemberRoleBody,
} from "../model";

import { fetchWithAuth } from ".././fetchWithAuth";

export type getOrganizationsRolesResponse200 = {
  data: GetOrganizationsRoles200Item[];
  status: 200;
};

export type getOrganizationsRolesResponseSuccess =
  getOrganizationsRolesResponse200 & {
    headers: Headers;
  };
export type getOrganizationsRolesResponse =
  getOrganizationsRolesResponseSuccess;

export const getGetOrganizationsRolesUrl = () => {
  return `${apiURL}/api/organizations/roles`;
};

export const getOrganizationsRoles = async (
  options?: Parameters<typeof fetchWithAuth>[1],
): Promise<getOrganizationsRolesResponse> => {
  return fetchWithAuth<getOrganizationsRolesResponse>(
    getGetOrganizationsRolesUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export type getOrganizationsMeResponse200 = {
  data: GetOrganizationsMe200Item[];
  status: 200;
};

export type getOrganizationsMeResponse401 = {
  data: NotConnectedResponse;
  status: 401;
};

export type getOrganizationsMeResponseSuccess =
  getOrganizationsMeResponse200 & {
    headers: Headers;
  };
export type getOrganizationsMeResponseError = getOrganizationsMeResponse401 & {
  headers: Headers;
};

export type getOrganizationsMeResponse =
  getOrganizationsMeResponseSuccess | getOrganizationsMeResponseError;

export const getGetOrganizationsMeUrl = () => {
  return `${apiURL}/api/organizations/me`;
};

export const getOrganizationsMe = async (
  options?: Parameters<typeof fetchWithAuth>[1],
): Promise<getOrganizationsMeResponse> => {
  return fetchWithAuth<getOrganizationsMeResponse>(getGetOrganizationsMeUrl(), {
    ...options,
    method: "GET",
  });
};

export type getOrganizationsByIdActivateResponse200 = {
  data: Organization;
  status: 200;
};

export type getOrganizationsByIdActivateResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type getOrganizationsByIdActivateResponse401 = {
  data: NotConnectedResponse;
  status: 401;
};

export type getOrganizationsByIdActivateResponseSuccess =
  getOrganizationsByIdActivateResponse200 & {
    headers: Headers;
  };
export type getOrganizationsByIdActivateResponseError = (
  | getOrganizationsByIdActivateResponse400
  | getOrganizationsByIdActivateResponse401
) & {
  headers: Headers;
};

export type getOrganizationsByIdActivateResponse =
  | getOrganizationsByIdActivateResponseSuccess
  | getOrganizationsByIdActivateResponseError;

export const getGetOrganizationsByIdActivateUrl = (id: number | string) => {
  return `${apiURL}/api/organizations/${id}/activate`;
};

/**
 * Active l'utilisateur invité dans l'organisation
 */
export const getOrganizationsByIdActivate = async (
  id: number | string,
  options?: Parameters<typeof fetchWithAuth>[1],
): Promise<getOrganizationsByIdActivateResponse> => {
  return fetchWithAuth<getOrganizationsByIdActivateResponse>(
    getGetOrganizationsByIdActivateUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

export type getOrganizationsByIdResponse200 = {
  data: Organization;
  status: 200;
};

export type getOrganizationsByIdResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getOrganizationsByIdResponseSuccess =
  getOrganizationsByIdResponse200 & {
    headers: Headers;
  };
export type getOrganizationsByIdResponseError =
  getOrganizationsByIdResponse404 & {
    headers: Headers;
  };

export type getOrganizationsByIdResponse =
  getOrganizationsByIdResponseSuccess | getOrganizationsByIdResponseError;

export const getGetOrganizationsByIdUrl = (id: number | string) => {
  return `${apiURL}/api/organizations/${id}`;
};

/**
 * Récupérer les données de l'organisation. NB : si pas membre, seul un décompte des membres est fourni.
 */
export const getOrganizationsById = async (
  id: number | string,
  options?: Parameters<typeof fetchWithAuth>[1],
): Promise<getOrganizationsByIdResponse> => {
  return fetchWithAuth<getOrganizationsByIdResponse>(
    getGetOrganizationsByIdUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

export type deleteOrganizationResponse204 = {
  data: DeletedResponse;
  status: 204;
};

export type deleteOrganizationResponse401 = {
  data: NotConnectedResponse;
  status: 401;
};

export type deleteOrganizationResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type deleteOrganizationResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type deleteOrganizationResponseSuccess =
  deleteOrganizationResponse204 & {
    headers: Headers;
  };
export type deleteOrganizationResponseError = (
  | deleteOrganizationResponse401
  | deleteOrganizationResponse403
  | deleteOrganizationResponse404
) & {
  headers: Headers;
};

export type deleteOrganizationResponse =
  deleteOrganizationResponseSuccess | deleteOrganizationResponseError;

export const getDeleteOrganizationUrl = (id: number | string) => {
  return `${apiURL}/api/organizations/${id}`;
};

/**
 * Supprime l'organisation d'identifiant id
 */
export const deleteOrganization = async (
  id: number | string,
  options?: Parameters<typeof fetchWithAuth>[1],
): Promise<deleteOrganizationResponse> => {
  return fetchWithAuth<deleteOrganizationResponse>(
    getDeleteOrganizationUrl(id),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export type postOrganizationResponse201 = {
  data: Organization;
  status: 201;
};

export type postOrganizationResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type postOrganizationResponse401 = {
  data: NotConnectedResponse;
  status: 401;
};

export type postOrganizationResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type postOrganizationResponseSuccess = postOrganizationResponse201 & {
  headers: Headers;
};
export type postOrganizationResponseError = (
  | postOrganizationResponse400
  | postOrganizationResponse401
  | postOrganizationResponse403
) & {
  headers: Headers;
};

export type postOrganizationResponse =
  postOrganizationResponseSuccess | postOrganizationResponseError;

export const getPostOrganizationUrl = () => {
  return `${apiURL}/api/organizations`;
};

/**
 * Créer une organisation - L'utilisateur connecté devient un propriétaire
 */
export const postOrganization = async (
  postOrganizationBody: PostOrganizationBody,
  options?: Parameters<typeof fetchWithAuth>[1],
): Promise<postOrganizationResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return fetchWithAuth<postOrganizationResponse>(getPostOrganizationUrl(), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(postOrganizationBody),
  });
};

export type putOrganizationAttributeResponse200 = {
  data: PutOrganizationAttribute200;
  status: 200;
};

export type putOrganizationAttributeResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type putOrganizationAttributeResponse401 = {
  data: NotConnectedResponse;
  status: 401;
};

export type putOrganizationAttributeResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type putOrganizationAttributeResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type putOrganizationAttributeResponseSuccess =
  putOrganizationAttributeResponse200 & {
    headers: Headers;
  };
export type putOrganizationAttributeResponseError = (
  | putOrganizationAttributeResponse400
  | putOrganizationAttributeResponse401
  | putOrganizationAttributeResponse403
  | putOrganizationAttributeResponse404
) & {
  headers: Headers;
};

export type putOrganizationAttributeResponse =
  | putOrganizationAttributeResponseSuccess
  | putOrganizationAttributeResponseError;

export const getPutOrganizationAttributeUrl = (
  id: number | string,
  attribute: string,
) => {
  return `${apiURL}/api/organizations/${id}/${attribute}`;
};

/**
 * Affecte value à l'attribut de l'organisation d'identifiant public_id
 */
export const putOrganizationAttribute = async (
  id: number | string,
  attribute: string,
  putOrganizationAttributeBody: PutOrganizationAttributeBody,
  options?: Parameters<typeof fetchWithAuth>[1],
): Promise<putOrganizationAttributeResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return fetchWithAuth<putOrganizationAttributeResponse>(
    getPutOrganizationAttributeUrl(id, attribute),
    {
      ...options,
      method: "PUT",
      headers: {
        "Content-Type": "application/json",
        ...getHeaders(options?.headers),
      },
      body: JSON.stringify(putOrganizationAttributeBody),
    },
  );
};

export type putOrganizationJoinLinkRoleResponse200 = {
  data: PutOrganizationJoinLinkRole200;
  status: 200;
};

export type putOrganizationJoinLinkRoleResponse401 = {
  data: NotConnectedResponse;
  status: 401;
};

export type putOrganizationJoinLinkRoleResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type putOrganizationJoinLinkRoleResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type putOrganizationJoinLinkRoleResponseSuccess =
  putOrganizationJoinLinkRoleResponse200 & {
    headers: Headers;
  };
export type putOrganizationJoinLinkRoleResponseError = (
  | putOrganizationJoinLinkRoleResponse401
  | putOrganizationJoinLinkRoleResponse403
  | putOrganizationJoinLinkRoleResponse404
) & {
  headers: Headers;
};

export type putOrganizationJoinLinkRoleResponse =
  | putOrganizationJoinLinkRoleResponseSuccess
  | putOrganizationJoinLinkRoleResponseError;

export const getPutOrganizationJoinLinkRoleUrl = (
  id: number | string,
  role: string,
) => {
  return `${apiURL}/api/organizations/${id}/join-link/${role}`;
};

/**
 * Modifie le lien d'accès à l'organisation
 */
export const putOrganizationJoinLinkRole = async (
  id: number | string,
  role: string,
  putOrganizationJoinLinkRoleBody: PutOrganizationJoinLinkRoleBody,
  options?: Parameters<typeof fetchWithAuth>[1],
): Promise<putOrganizationJoinLinkRoleResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return fetchWithAuth<putOrganizationJoinLinkRoleResponse>(
    getPutOrganizationJoinLinkRoleUrl(id, role),
    {
      ...options,
      method: "PUT",
      headers: {
        "Content-Type": "application/json",
        ...getHeaders(options?.headers),
      },
      body: JSON.stringify(putOrganizationJoinLinkRoleBody),
    },
  );
};

export type joinOrganizationByIdResponse200 = {
  data: Organization;
  status: 200;
};

export type joinOrganizationByIdResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type joinOrganizationByIdResponse401 = {
  data: NotConnectedResponse;
  status: 401;
};

export type joinOrganizationByIdResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type joinOrganizationByIdResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type joinOrganizationByIdResponseSuccess =
  joinOrganizationByIdResponse200 & {
    headers: Headers;
  };
export type joinOrganizationByIdResponseError = (
  | joinOrganizationByIdResponse400
  | joinOrganizationByIdResponse401
  | joinOrganizationByIdResponse403
  | joinOrganizationByIdResponse404
) & {
  headers: Headers;
};

export type joinOrganizationByIdResponse =
  joinOrganizationByIdResponseSuccess | joinOrganizationByIdResponseError;

export const getJoinOrganizationByIdUrl = (id: number | string) => {
  return `${apiURL}/api/organizations/join/${id}`;
};

/**
 * L'utilisateur s'ajoute à l'organisation via le jeton id
 */
export const joinOrganizationById = async (
  id: number | string,
  options?: Parameters<typeof fetchWithAuth>[1],
): Promise<joinOrganizationByIdResponse> => {
  return fetchWithAuth<joinOrganizationByIdResponse>(
    getJoinOrganizationByIdUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

export type getOrganizationLinksByIdResponse200 = {
  data: GetOrganizationLinksById200;
  status: 200;
};

export type getOrganizationLinksByIdResponse401 = {
  data: NotConnectedResponse;
  status: 401;
};

export type getOrganizationLinksByIdResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type getOrganizationLinksByIdResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getOrganizationLinksByIdResponseSuccess =
  getOrganizationLinksByIdResponse200 & {
    headers: Headers;
  };
export type getOrganizationLinksByIdResponseError = (
  | getOrganizationLinksByIdResponse401
  | getOrganizationLinksByIdResponse403
  | getOrganizationLinksByIdResponse404
) & {
  headers: Headers;
};

export type getOrganizationLinksByIdResponse =
  | getOrganizationLinksByIdResponseSuccess
  | getOrganizationLinksByIdResponseError;

export const getGetOrganizationLinksByIdUrl = (id: number | string) => {
  return `${apiURL}/api/organizations/links/${id}`;
};

/**
 * Récupère les liens d'invitation de l'organisation. Seuls les propriétaires peuvent accéder à cette ressource.
 */
export const getOrganizationLinksById = async (
  id: number | string,
  options?: Parameters<typeof fetchWithAuth>[1],
): Promise<getOrganizationLinksByIdResponse> => {
  return fetchWithAuth<getOrganizationLinksByIdResponse>(
    getGetOrganizationLinksByIdUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

export type addMemberToOrganizationResponse200 = {
  data: AddMemberToOrganization200;
  status: 200;
};

export type addMemberToOrganizationResponse401 = {
  data: NotConnectedResponse;
  status: 401;
};

export type addMemberToOrganizationResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type addMemberToOrganizationResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type addMemberToOrganizationResponseSuccess =
  addMemberToOrganizationResponse200 & {
    headers: Headers;
  };
export type addMemberToOrganizationResponseError = (
  | addMemberToOrganizationResponse401
  | addMemberToOrganizationResponse403
  | addMemberToOrganizationResponse404
) & {
  headers: Headers;
};

export type addMemberToOrganizationResponse =
  addMemberToOrganizationResponseSuccess | addMemberToOrganizationResponseError;

export const getAddMemberToOrganizationUrl = (
  id: number | string,
  userId: string,
) => {
  return `${apiURL}/api/organizations/${id}/members/${userId}`;
};

/**
 * Ajoute un membre à l'organisation
 */
export const addMemberToOrganization = async (
  id: number | string,
  userId: string,
  addMemberToOrganizationBody: AddMemberToOrganizationBody,
  options?: Parameters<typeof fetchWithAuth>[1],
): Promise<addMemberToOrganizationResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return fetchWithAuth<addMemberToOrganizationResponse>(
    getAddMemberToOrganizationUrl(id, userId),
    {
      ...options,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...getHeaders(options?.headers),
      },
      body: JSON.stringify(addMemberToOrganizationBody),
    },
  );
};

export type deleteOrganizationMemberResponse204 = {
  data: DeletedResponse;
  status: 204;
};

export type deleteOrganizationMemberResponse401 = {
  data: NotConnectedResponse;
  status: 401;
};

export type deleteOrganizationMemberResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type deleteOrganizationMemberResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type deleteOrganizationMemberResponseSuccess =
  deleteOrganizationMemberResponse204 & {
    headers: Headers;
  };
export type deleteOrganizationMemberResponseError = (
  | deleteOrganizationMemberResponse401
  | deleteOrganizationMemberResponse403
  | deleteOrganizationMemberResponse404
) & {
  headers: Headers;
};

export type deleteOrganizationMemberResponse =
  | deleteOrganizationMemberResponseSuccess
  | deleteOrganizationMemberResponseError;

export const getDeleteOrganizationMemberUrl = (
  id: number | string,
  userId: string,
) => {
  return `${apiURL}/api/organizations/${id}/members/${userId}`;
};

/**
 * Enlève un membre de l'organisation. Un utilisateur peut se retirer lui-même, sinon un owner doit effectuer cette action.
 */
export const deleteOrganizationMember = async (
  id: number | string,
  userId: string,
  options?: Parameters<typeof fetchWithAuth>[1],
): Promise<deleteOrganizationMemberResponse> => {
  return fetchWithAuth<deleteOrganizationMemberResponse>(
    getDeleteOrganizationMemberUrl(id, userId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export type putOrganizationMemberRoleResponse200 = {
  data: PutOrganizationMemberRole200;
  status: 200;
};

export type putOrganizationMemberRoleResponse401 = {
  data: NotConnectedResponse;
  status: 401;
};

export type putOrganizationMemberRoleResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type putOrganizationMemberRoleResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type putOrganizationMemberRoleResponseSuccess =
  putOrganizationMemberRoleResponse200 & {
    headers: Headers;
  };
export type putOrganizationMemberRoleResponseError = (
  | putOrganizationMemberRoleResponse401
  | putOrganizationMemberRoleResponse403
  | putOrganizationMemberRoleResponse404
) & {
  headers: Headers;
};

export type putOrganizationMemberRoleResponse =
  | putOrganizationMemberRoleResponseSuccess
  | putOrganizationMemberRoleResponseError;

export const getPutOrganizationMemberRoleUrl = (
  id: number | string,
  userId: string,
) => {
  return `${apiURL}/api/organizations/${id}/members/${userId}/role`;
};

/**
 * Modifie le rôle d'un membre dans l'organisation
 */
export const putOrganizationMemberRole = async (
  id: number | string,
  userId: string,
  putOrganizationMemberRoleBody: PutOrganizationMemberRoleBody,
  options?: Parameters<typeof fetchWithAuth>[1],
): Promise<putOrganizationMemberRoleResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return fetchWithAuth<putOrganizationMemberRoleResponse>(
    getPutOrganizationMemberRoleUrl(id, userId),
    {
      ...options,
      method: "PUT",
      headers: {
        "Content-Type": "application/json",
        ...getHeaders(options?.headers),
      },
      body: JSON.stringify(putOrganizationMemberRoleBody),
    },
  );
};
