name: Ajouter au projet "Suivi global Cartes.gouv" si label "suivi" est ajouté

on:
  issues:
    types: opened
  pull_request:
    types: opened

jobs:
  add-to-project:
    name: Ajoute issue au projet Suivi global si label suivi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/IGNF/projects/53
          github-token: ${{ secrets.GH_PAT }}
          labeled: suivi
          
