name: Ajouter au projet "Suivi global Cartes.gouv" si label "suivi" est ajouté

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]

jobs:
  add-to-project:
    if: contains(github.event.issue.labels.*.name, 'suivi')
    runs-on: ubuntu-latest

    permissions:
      repository-projects: write

    steps:
    - name: Trouver le projet Suivi global
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ORGANIZATION: IGNF
        PROJECT_NUMBER: 53
      run: |
        gh api graphql -f query='
          query($org: String!, $number: Int!) {
            organization(login: $org){
              projectV2(number: $number) {
                id
              }
            }
          }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER > project_data.json

        echo 'PROJECT_ID='$(jq '.data.organization.projectV2.id' project_data.json) >> $GITHUB_ENV
          
    - name: Ajouter l’issue au projet Suivi global
      run: |
        item_id="$( gh api graphql -f query='
          mutation($project:ID!, $issue:ID!) {
            addProjectV2ItemById(input: {projectId: $project, contentId: $issue}) {
              item {
                id
              }
            }
          }' -f project=$PROJECT_ID -f issue=$ISSUE_ID --jq '.data.addProjectV2ItemById.item.id')" 
